spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true # Set to true to see SQL statements in logs

