spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update # You can change this to your desired value (e.g., create, update, none)
    show-sql: true # Set to true to see SQL statements in logs
  application:
    name: ORDER-SERVICE

server:
  port: 8082 # Change to the desired port for your Spring Boot application

logging:
  level:
    root: INFO # Adjust log levels as needed for your application
