version: '3'
services:
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #   - "2182:2182"
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    # environment:
    #   KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
    #   KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
    #   KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'