

server:
  port: 8070

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: schools

  config:
    import: optional:configserver:http://localhost:8888
    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schools
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

application: 
  config:
    students-url: http://localhost:8090/api/v1/students