
spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/product_db # Database connection details
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
    loadbalancer:
      ribbon:
        enabled: false # Disable Ribbon if using Spring Cloud Load Balancer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka server URL
